### ISSUE TITLE
check fails on piezo pin

### ISSUE THREAD

**Issue by sputnik63** [MrYsLab/xi#8]
on xiserver.js:455 the check `piezoArray[i].pin === pin` fails since `typeof(piezoArray[i].pin)` is 'number' but `typeof(pin)` is string.
The solution could be to change the line xiserver.js:438 from `pin = msg[2]` to `pin = parseInt(msg[2])` as it's already done in case moveStandardServo and moveContinuousServo
The problem occurs in line 471, with same solution.

**Comment by MrYsLab** [comment]
Thanks, I will take a look. Although I don't think this is a problem, what version of node are you running? I won't be able to get to this until after June 1, but I will definitely get back to you.

**Comment by sputnik63** [comment]
I'm running the v0.10.44 :( due to some costraints in some libraries required.
By the way I made that fix on my local file and now it works.
I'm trying to use xiserver with my linux based boards with Scratch

**Comment by MrYsLab** [comment]
Thanks for letting me know. I have not tried either the RPi or BBB code in quite a while. When I did test it, I was running wheezy at the time, but Jessie may work. Feel free to issue a pull request if you wish. In either case, I will be testing and updating soon after June 1.

Thanks again.

**Comment by MrYsLab** [comment]
@sputnik63 I just tested the code both on Scratch and Snap! on Linux and I do not get this error. I am using node version 4.3.2. I did a fresh install and cannot recreate the problem. Since you have already modified the code to work for you, I am closing this issue. If you wish to reopen the issue, just let me know.
